# Generated by Django 3.0.3 on 2021-11-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reguser',
            name='email',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
