# Generated by Django 3.0.3 on 2021-11-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_auto_20211113_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='reguser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
