# Generated by Django 3.0.3 on 2021-11-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0003_reguser_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reguser',
            name='last_login',
        ),
        migrations.AddField(
            model_name='reguser',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
