# Generated by Django 3.2.9 on 2021-11-29 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0005_auto_20211129_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reguser',
            name='last_login',
        ),
    ]
