# Generated by Django 3.2.9 on 2021-12-13 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0007_auto_20211213_2045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegUser',
        ),
    ]
