# Generated by Django 3.2.9 on 2021-12-14 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0011_auto_20211213_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
