# Generated by Django 3.2.9 on 2021-12-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0015_worksheets_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheets',
            name='filepath',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
