# Generated by Django 3.2.9 on 2021-12-17 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0016_alter_worksheets_filepath'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='worksheets',
            table='Worksheets',
        ),
    ]
