# Generated by Django 3.2.9 on 2021-12-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0017_alter_worksheets_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheets',
            name='filepath',
            field=models.FileField(null=True, upload_to='worksheets/'),
        ),
    ]
