# Generated by Django 3.2.9 on 2021-12-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0018_alter_worksheets_filepath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksheets',
            name='id',
        ),
        migrations.AddField(
            model_name='worksheets',
            name='worksheetID',
            field=models.CharField(default=1, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
