# Generated by Django 3.2.9 on 2021-12-18 08:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0019_auto_20211218_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheets',
            name='worksheetID',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
