# Generated by Django 3.2.9 on 2021-12-18 08:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0020_alter_worksheets_worksheetid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheets',
            name='worksheetID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
