# Generated by Django 3.2.9 on 2021-12-18 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0022_auto_20211218_1407'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='worksheets',
            table=None,
        ),
    ]
