# Generated by Django 3.2.9 on 2021-12-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0023_alter_worksheets_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheets',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='worksheets',
            name='price',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='worksheets',
            name='school',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
