# Generated by Django 3.2.9 on 2021-12-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0026_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='grade_level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profileid',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='school',
        ),
        migrations.AddField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
