# Generated by Django 3.2.9 on 2021-12-24 11:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0028_auto_20211223_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_table',
            name='id',
        ),
        migrations.AddField(
            model_name='register_table',
            name='profileid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
