# Generated by Django 3.2.9 on 2021-12-25 05:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0029_auto_20211224_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechTool',
            fields=[
                ('toolID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=500)),
                ('tool', models.CharField(max_length=500)),
                ('logo', models.FileField(null=True, upload_to='edtechtool/')),
                ('grade_level', models.CharField(max_length=500)),
                ('concept', models.CharField(max_length=500)),
                ('links', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
