# Generated by Django 3.2.9 on 2021-12-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0030_techtool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='techtool',
            old_name='links',
            new_name='link1',
        ),
        migrations.AddField(
            model_name='techtool',
            name='link2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='techtool',
            name='link3',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
