# Generated by Django 3.2.9 on 2021-12-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0031_auto_20211225_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='techtool',
            name='guide',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
