# Generated by Django 3.2.9 on 2021-12-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0032_techtool_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techtool',
            name='logo',
            field=models.ImageField(null=True, upload_to='edtechtool/'),
        ),
    ]
